version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432
    env_file: .env
  redis:
    image: redis
    ports:
      - 6379
  back:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file: .env