version: "3.7"

services:
  postgres:
    image: postgres
    restart: on-failure
    ports:
      - 5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379
  back:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - POSTGRES_HOST="postgres"
      - REDIS_HOST="redis"
volumes:
  postgres_data:
