version: "3"

services:
  postgres:
    image: postgres
    ports:
      - 5432
    env_file: .env
  redis:
    image: redis
    ports:
      - 6379
  back:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - POSTGRES_HOST = "postgres"
      - REDIS_HOST = "redis"
