# Generated by Django 3.0.6 on 2021-03-15 23:22

import app.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertask',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='finish_work_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=64, unique=True, validators=[app.core.validators.CustomUsernameValidator]),
        ),
        migrations.AlterField(
            model_name='pack',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='socket_channel_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='answer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
