# Generated by Django 3.0.6 on 2020-12-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201206_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='usertaskroom',
            name='likes',
            field=models.ManyToManyField(related_name='liked_answers', to='core.Player'),
        ),
    ]
